### ISSUE TITLE
fix challenge related description in README.md

### ISSUE THREAD

**Issue by zhaohaijun** [LambdaIM/proofDP#11]
Change Description

**Comment by Tjan147** [comment]
@zhaohaijun picks this issue from **[Create tag & challenge for data](https://github.com/LambdaIM/proofDP#create-tag--challenge-for-data)** description.

According to the [paper](https://doi.org/10.1109/TC.2011.245), TPA is responsible for challenging the cloud server for data possession. Thus, current `GenChallenge()` implementation is misleading.
